Writer and WriterT documentation site pages
typelevel/cats pull request #3618
Opened 2020-09-28 23:49 UTC by benkio

Please be patient, I'm a non native english speaker. Basically the less qualified man for the job. Any feedback appreciated and I'll fix it ASAP

2020-10-10 09:59 UTC, larsrh requested changes
Thanks a lot for this! I have only a few minor comments and suggestions.

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writer.md
> +The `Writer[L, A]` datatype represents a computation that produce a
```suggestion
The `Writer[L, A]` datatype represents a computation that produces a
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writer.md
> +The main features the `Writer` provides are:
```suggestion
The main features that `Writer` provides are:
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writer.md
> +  logs of both functions will be combined using an implicit [Semigroup](https://typelevel.org/cats/typeclasses/semigroup.html).
Both are good points, but if it's an enumeration, the structure of the sentences should be similar. I suggest removing the bullet points and rephrasing it as a paragraph.

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writer.md
> +The `Writer` datatype provides a set of functions that are quite
"quite identical" → "similar to"

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writer.md
> +the same name and the same signature, but for the requirement of a
```suggestion
the same name and the same signature, but have an additional requirement of a
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writer.md
> +`map` effects only the value, keeping the log side untouched. Plus, here we show `run`
```suggestion
`map` affects only the value, keeping the log side untouched. Plus, here we show `run`
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writert.md
> +`F[Writer[L, V]]` directly, this because it exposes operations that allow
```suggestion
`F[Writer[L, V]]` directly, because it exposes operations that allow
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writert.md
> +since it as a slightly different behaviour then
```suggestion
since it as a slightly different behaviour than
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writert.md
> +A `WriterT` can be built starting from multiple values. Here is the
```suggestion
A `WriterT` can be constructed in different ways. Here is the
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writert.md
> +Into the [Writer
```suggestion
In the [Writer
```

2020-10-10 09:59 UTC, larsrh commented on docs/src/main/mdoc/datatypes/writert.md
> +As en example, we can consider a simple naive console application that
```suggestion
As an example, we can consider a simple naive console application that
```

2020-10-10 19:56 UTC, benkio commented
> Thanks a lot for this! I have only a few minor comments and suggestions.

Comments addressed :+1: Thank you

2020-10-12 06:09 UTC, larsrh approved these changes

2020-10-12 19:46 UTC, LukaJCB approved these changes
Thanks so much for working on this!

2020-10-12 19:47 UTC, merged