specialized EqOps
typelevel/cats pull request #3702
Opened 2020-12-01 10:09 UTC by YannMoisan

- `1L === 2L` triggers boxing of both longs and so costs 2 allocations
- `Eq.eqv(1L, 2L)` do not trigger boxing because `Eq` is specialized

This PR aims at fixing that by specializing also `EqOps`

2020-12-01 13:28 UTC, YannMoisan commented
retest

2020-12-01 14:49 UTC, djspiewak commented
At present, Scala 3 doesn't support specialization, so this will need to be source tree specific. I do think this is a good idea though, particularly since Eq itself is already specialized!

2020-12-01 15:16 UTC, djspiewak requested changes
You'll also need to add a non-specialized version of `EqOps` within the scala-3.x source directory. Also worth noting that you only need to push `EqOps` into the scala version-specific directories; `EqSyntax` works across both.

2020-12-01 15:16 UTC, djspiewak commented on core/src/main/scala-2.x/src/main/scala/cats/syntax/eq.scala
> +package src.main.scala.cats.syntax
:-) I think intellij is drunk.

2020-12-03 15:24 UTC, YannMoisan commented
@djspiewak I've fixed the PR

2020-12-03 15:42 UTC, LukaJCB approved these changes
thanks!

2020-12-08 20:46 UTC, YannMoisan commented
@djspiewak Just in case you miss the notification, the requested changes have been taken into account.

2020-12-19 12:59 UTC, larsrh approved these changes

2020-12-19 12:59 UTC, merged

2020-12-19 12:59 UTC, larsrh commented
Thanks, @YannMoisan!

2021-02-10 07:15 UTC, larsrh commented
This change is source-breaking, whenever someone overrides it:

```
[error] /home/runner/work/cats-testkit-scalatest/cats-testkit-scalatest/core/src/main/scala/cats/tests/CatsSuite.scala:61:29: Type parameter has to be specialized at least for the same types as in the overridden method. Missing types: Double, Float, Int, Long
[error]   override def catsSyntaxEq[A: Eq](a: A): EqOps[A] = new EqOps[A](a)
[error]                             ^
```

Unfortunately it also demands that anyone who overrides it has to do it depending on the Scala version.