Add NonEmptyList.min and NonEmptyList.max
typelevel/cats pull request #3935
Opened 2021-07-07 11:19 UTC by JannikArndt

This adds `.min` and `.max` to `NonEmptyList[A]` if there's an Ordering for `A`.

---------

Background: We ran into the issue that scapegoat complained that `List(a, b, c).min` isn't safe. Since we _know_ the list is not empty, we tried `NonEmptyList`, but `min` and `max` don't exist there. 

The implementation uses `reduceLeft`, same as the standard lib for `IterableOnce`: https://github.com/scala/scala/blob/262c97250a614bf19a0e9e8994ee59abea82a5db/src/library/scala/collection/IterableOnce.scala#L912-L916

Note: I did run `+prePR`, and it failed in `free/src/main/scala-3.x/cats/free/FreeFoldStep.scala`, but not in any file touched by this PR.

2021-07-09 01:46 UTC, johnynek requested changes

2021-07-09 01:46 UTC, johnynek commented on core/src/main/scala/cats/data/NonEmptyList.scala
> +  def min[AA >: A](implicit ord: Ordering[AA]): A = reduceLeft(ord.min[A])
This should be a cats.Order.

2021-07-09 01:46 UTC, johnynek commented on core/src/main/scala/cats/data/NonEmptyList.scala
> +  def max[AA >: A](implicit ord: Ordering[AA]): A = reduceLeft(ord.max[A])
cats.Order

2021-07-09 02:02 UTC, rossabaker commented on tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
> +
After @posco's suggestions, which I agree with, these properties assume `Order` and `Ordering` are consistent.  That holds for `Int`, and I can't think of a counterexample.  But that assumption might be worth a comment.

Vaguely related discussion: #3936.

2021-07-15 15:15 UTC, JannikArndt commented
#3937 solves the problem in a nicer way

2021-07-15 15:15 UTC, closed without merging