Make StackSafeMonad extend Defer
typelevel/cats pull request #3962
Opened 2021-08-10 05:36 UTC by johnynek

Make StackSafeMonad extend Defer.

See the discussion in #3790 for more context.

The argument for why this is safe is given in the comments on StackSafeMonad. If they don't seem to make sense, please add a comment there.

cc @djspiewak @non 

I think we can follow up with using an idea similar to `shift` from Kleisli to make an Applicative map2 abstraction. As a sketch:

```scala
trait Map2Strategy[F[_]] {
  type Lazy[_]
  def map2[A, B](fa: F[A], fb: Lazy[F[B]]): Lazy[F[B]]
}
```
and then we can either make `Lazy[A] = Eval[A]` or `Lazy[A] = Id[A]` depending on the `F[_]` which maybe we can reflectively select based on if the `F[_]` is a `StackSafeMonad` or not.

Or something...

2021-08-10 14:35 UTC, djspiewak requested changes
I like where this is going. I had a similar thought around the `Lazy[_]` idea but still trying to piece through how we can make it not-horrible.

2021-08-10 14:35 UTC, djspiewak commented on core/src/main/scala/cats/StackSafeMonad.scala
> +    }
I wonder if there's a way to make this more general. `A => F[B]` works extremely well for `Kleisli` and extremely not-well for almost anything else, since it will force boxing into a `Function1` in cases where it just isn't needed.

2021-08-10 14:35 UTC, djspiewak commented on core/src/main/scala/cats/instances/tailrec.scala
>      new StackSafeMonad[TailRec] with Defer[TailRec] {
```suggestion
  val catsInstancesForTailRec: StackSafeMonad[TailRec] =
    new StackSafeMonad[TailRec] {
```

Minor cleanup…

2021-08-10 14:35 UTC, djspiewak commented on core/src/main/scala/cats/StackSafeMonad.scala
> +  /**
```suggestion
  /*
```

Can we actually make this *not* scaladoc? The problem here is if we make it a scaladoc comment, it will override the inherited one from `Defer`, which in turn results in *this* being the documentation shown in downstream generated scaladoc.

2021-09-12 23:16 UTC, johnynek commented on core/src/main/scala/cats/StackSafeMonad.scala
> +    }
Maybe it shouldn't be public at all. I just took what was in Kleisli and made it more particular. I think the current Kleisli hack is adding cost for any Monad that isn't lazy (e.g. Option, or Either), and this function will help there.

2021-09-13 01:50 UTC, johnynek commented
@djspiewak please take a look and see what you think with your changes merged.

2021-11-17 05:01 UTC, rossabaker commented on core/src/main/scala/cats/StackSafeMonad.scala
> +    }
When in doubt, leave it private.  Can always publicize it later if someone finds a second use.

2025-07-06 02:05 UTC, closed without merging