Documentation/update adopters & contibuting
typelevel/cats pull request #4124
Opened 2022-02-02 10:47 UTC by benkio

Updated Adopters sections to this day based on #1099
All Adopters entries capitalised and alphabetically ordered
Update the `CONTRIBUTING.md` / Generating the Site, mentioning the specific scala-version to use, plus the reference links to the CI workflow

2022-02-02 16:09 UTC, rossabaker approved these changes

2022-02-02 18:32 UTC, johnynek requested changes

2022-02-02 18:32 UTC, johnynek commented on README.md
> +- [Stripe](https://stripe.com/)
is stripe listed twice? looks like.

2022-02-02 18:32 UTC, johnynek commented on README.md
> +- [The Walt Disney Company](https://www.disney.com)
this is also listed above as `Disney`

2022-02-08 17:29 UTC, armanbilge approved these changes

2022-02-08 18:29 UTC, rossabaker approved these changes

2022-02-08 22:51 UTC, merged